#!/bin/bash
#SBATCH --job-name=nanoAOD_array       # Name of the job array
#SBATCH --output=/home/shar1172/CustomNanoAOD/logs_differnt_nevent_UL2016_25March/nanoAOD_%A_%a.out   # Output file for each task (%A is the job array ID, %a is the task ID)
#SBATCH --error=/home/shar1172/CustomNanoAOD/logs_differnt_nevent_UL2016_25March/nanoAOD_%A_%a.err    # Error file for each task
#SBATCH --account=cms
#SBATCH --partition=cpu
#SBATCH --qos=standby
#SBATCH --array=1-10                    # Task array range (modify this according to your input file count): Total 10948 files
#SBATCH --ntasks=1                     # Number of tasks per job
#SBATCH --cpus-per-task=1              # Number of CPUs per task
#SBATCH --mem=2010                    # Memory per task
#SBATCH --time=03:50:00                # Max run time for each task (HH:MM:SS)
#SBATCH --get-user-env                 # Get environment variables for the job

configFile=$(sed -n "${SLURM_ARRAY_TASK_ID}p" skim_df_DifferentNEvents_2016_14March.csv | awk '{print $1}')
inputMiniAOD=$(sed -n "${SLURM_ARRAY_TASK_ID}p" skim_df_DifferentNEvents_2016_14March.csv | awk '{print $2}')
outputDirectory=$(sed -n "${SLURM_ARRAY_TASK_ID}p" skim_df_DifferentNEvents_2016_14March.csv | awk '{print $3}')
nEvents=$(sed -n "${SLURM_ARRAY_TASK_ID}p" skim_df_DifferentNEvents_2016_14March.csv | awk '{print $4}')

# Define NanoAOD output file path
outputNanoAOD="${outputDirectory}/$(basename ${inputMiniAOD} .root)_NanoAOD.root"

# Sleep to avoid overloading the EOS file system
SleepTime=$((SLURM_ARRAY_TASK_ID * 30))
if [ $SleepTime -gt 900 ]; then # keep SleepTime within 900 seconds
    SleepTime=$((SleepTime % 900))
fi
echo "Sleeping for $SleepTime seconds"
sleep $SleepTime
echo "Job started after sleep at $(date)"
echo "Processing job ${SLURM_ARRAY_TASK_ID} with input file: ${inputMiniAOD}"

# # Set up the environment before running the script
# echo "Setting up the environment..."

# # Setup conda and fetch python3 environment
# source /etc/profile.d/modules.sh
# module --force purge
# module load conda/2024.09
# conda activate /depot/cms/kernels/python3

# # Setup CMSSW environment & related commands
# source /cvmfs/cms.cern.ch/cmsset_default.sh

# # Check if the NanoAOD file exists
# echo "Checking if NanoAOD file exists: $outputNanoAOD"

# # Run gfal-ls to check if the NanoAOD file exists
# gfal-ls $outputNanoAOD > /dev/null 2>&1
# if [ $? -ne 0 ]; then
#     echo "NanoAOD file does not exist: $outputNanoAOD"
#     echo "Job will run the full processing script."
# else
#     # If NanoAOD exists, compare events between MiniAOD and NanoAOD
#     python3 compare_miniAOD_nanoAOD_totalEvents.py $inputMiniAOD $outputDirectory
#     if [ $? -eq 0 ]; then
#         echo "Total events are the same in MiniAOD and NanoAOD. Exiting job."
#         exit 0  # Exit job if events match
#     else
#         echo "Total events are different in MiniAOD and NanoAOD. Running the full processing job."
#     fi
# fi

# Run the main script if events are different or NanoAOD doesn't exist
echo "Running the main processing script"
echo "bash condorjob_HMuMu_UL2018.sh $SLURM_ARRAY_TASK_ID $SLURM_ARRAY_TASK_ID $configFile $inputMiniAOD $outputDirectory $nEvents"
bash condorjob_HMuMu_UL2018.sh $SLURM_ARRAY_TASK_ID $SLURM_ARRAY_TASK_ID $configFile $inputMiniAOD $outputDirectory $nEvents
echo "Job finished at $(date)"
