#!/bin/bash
#SBATCH --job-name=nanoAOD_array       # Name of the job array
#SBATCH --output=/home/shar1172/CustomNanoAOD/logs_differnt_nevent_UL2018/nanoAOD_%A_%a.out   # Output file for each task (%A is the job array ID, %a is the task ID)
#SBATCH --error=/home/shar1172/CustomNanoAOD/logs_differnt_nevent_UL2018/nanoAOD_%A_%a.err    # Error file for each task
#SBATCH --account=cms
#SBATCH --partition=cpu
#SBATCH --qos=standby
#SBATCH --array=1-1959                    # Task array range (modify this according to your input file count) # Total 5390 files
#SBATCH --ntasks=1                     # Number of tasks per job
#SBATCH --cpus-per-task=4              # Number of CPUs per task
#SBATCH --mem=8000                    # Memory per task
#SBATCH --time=10:00:00                # Max run time for each task (HH:MM:SS)
#SBATCH --get-user-env                 # Get environment variables for the job


configFile=$(sed -n "${SLURM_ARRAY_TASK_ID}p" skim_df_DifferentNEvents_2018_14March.csv | awk '{print $1}')
inputMiniAOD=$(sed -n "${SLURM_ARRAY_TASK_ID}p" skim_df_DifferentNEvents_2018_14March.csv | awk '{print $2}')
outputDirectory=$(sed -n "${SLURM_ARRAY_TASK_ID}p" skim_df_DifferentNEvents_2018_14March.csv | awk '{print $3}')
nEvents=$(sed -n "${SLURM_ARRAY_TASK_ID}p" skim_df_DifferentNEvents_2018_14March.csv | awk '{print $4}')

# Sleep the jobs for a random time to avoid overloading the EOS file system
SleepTime=$((SLURM_ARRAY_TASK_ID * 30))
if [ $SleepTime -gt 900 ]; then # keep SleepTime within 900 seconds
    SleepTime=$((SleepTime % 900))
fi
echo "Sleeping for $SleepTime seconds"
sleep $SleepTime
echo "Job started after sleep at $(date)"
echo "Processing job ${SLURM_ARRAY_TASK_ID} with input file: ${inputMiniAOD}"

# Run the main script
echo "bash condorjob_HMuMu_UL2018.sh $SLURM_ARRAY_TASK_ID $SLURM_ARRAY_TASK_ID $configFile $inputMiniAOD $outputDirectory $nEvents"
bash condorjob_HMuMu_UL2018.sh $SLURM_ARRAY_TASK_ID $SLURM_ARRAY_TASK_ID $configFile $inputMiniAOD $outputDirectory $nEvents
echo "Job finished at $(date)"
